title: "[주간 회의] 날짜 "
labels: ["Meeting Minutes"]
body:
  - type: markdown
    attributes:
      value: |
        주간 회의록 템플릿
  - type: textarea
    id: meetingminutes_1
    attributes:
      label: 서비스별 사업 보고
      description: "서비스별 최근 28일까지의 각 상황에 대한 보고"
      value: |
        ## 서비스 상황 (최근 28일)
        ### 프로젝트명
        - DAU 당 세션수
        - DAU
        - 세션당 광고 노출:
        - ARPU:
        - 광고 요청 / 노출:
        - 스토어 등록정보 실적 (스토어 방문자, 획득, 전환율):
  - type: textarea
      id: meetingminutes_2
      attributes:
        label: 서비스별 개발 보고
        description: "서비스별 안드로이드 진행 상황 보고"
        value: |
          ## Android 진행 상황
          ### 프로젝트명
          > 프로젝트별 Android 진행 상황 링크 기재

          ### 지난주 주요 진행 작업
          - T.B.D

          ### 주요 잔여 작업
          - T.B.D
  - type: checkboxes
    attributes:
      label: Check that box!
      options:
        - label: This one!
          required: true
        - label: I won't stop you if you check this one, too
