title: "[주간 회의] 날짜 "
labels: ["Meeting Minutes"]
body:
  - type: markdown
    attributes:
      value: |
        # 서비스 현황
  - type: textarea
    id: meetingminutes_1
    attributes:
      label: 서비스별 사업 현황
      description: "서비스별 최근 28일까지의 각 현황 공유"
      value: |
        ## 서비스 상황 (최근 28일)
        ### 프로젝트명
        - DAU 당 세션수
        - DAU
        - 세션당 광고 노출:
        - ARPU:
        - 광고 요청 / 노출:
        - 스토어 등록정보 실적 (스토어 방문자, 획득, 전환율):
  - type: markdown
    attributes:
      value: |
        # 개발/디자인 진행 상황
  - type: textarea
    id: meetingminutes_and
    attributes:
      label: 서비스별 Android 개발 현황
      description: "서비스별 안드로이드 진행 현황"
      value: |
        ## Android 진행 상황
        ### 프로젝트명
        > 프로젝트별 Android 진행 상황 링크 기재

        ### 지난주 주요 진행 작업
        - T.B.D

        ### 주요 잔여 작업
        - T.B.D
  - type: textarea
    id: meetingminutes_iOS
    attributes:
      label: 서비스별 iOS 개발 현황
      description: "서비스별 iOS 진행 현황"
      value: |
        ## iOS 진행 상황
        ### 프로젝트명
        > 프로젝트별 iOS 진행 상황 링크 기재

        ### 지난주 주요 진행 작업
        - T.B.D

        ### 주요 잔여 작업
        - T.B.D
  - type: textarea
    id: meetingminutes_design
    attributes:
      label: 서비스별 디자인 현황
      description: "서비스별 디자인 진행 현황"
      value: |
        ## 디자인 진행 상황
        ### 프로젝트명
        > 프로젝트별 디자인 진행 상황 링크 기재

        ### 지난주 주요 진행 작업
        - T.B.D

        ### 주요 잔여 작업
        - T.B.D
  - type: markdown
    attributes:
      value: |
        # 기타 논의 안건
  - type: textarea
    id: meetingminutes_etc
    attributes:
      description: "기타 논의 안건 기재"
      value: |
        "> 기타 논의 안건을 편하게 업데이트 해주세요."
